### ISSUE TITLE
code check

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework2G5#11]
@yasmensarhan27 please check the milestone and read the description. Let me know if anything is not working.

**Comment by yasmensarhan27** [comment]
I'll do

**Comment by yasmensarhan27** [comment]
I think I've cleared it by mistake

**Comment by yasmensarhan27** [comment]
can you check please ??

**Comment by yasmensarhan27** [comment]
Checked and it works well

**Comment by sharmistharanit** [comment]
Yes, it is working.

**Comment by Mosaddeq107** [comment]
I think you should create another milestone. Because the deadline is approaching.

**Comment by yasmensarhan27** [comment]
Yes 
We will thank you for notifying us

**Comment by s4il3sh** [comment]
Thanks. @yasmensarhan27
