### ISSUE TITLE
What will the Algorithm part include for this project ?

### ISSUE THREAD

**Issue by yasmensarhan27** [ubsuny/23-Homework2G5#12]

**Comment by sharmistharanit** [comment]
I think that the algorithm part includes a generalized code for the unit test.

**Comment by Mosaddeq107** [comment]
@yasmensarhan27 , I think @sharmistharanit is right.

**Comment by Mosaddeq107** [comment]
@yasmensarhan27 Did you distribute your work among your group members?

**Comment by yasmensarhan27** [comment]
Yes 
I'm doing the documentation and unit test parts 
And sailesh is responsible for the maintenance and algorithm

**Comment by s4il3sh** [comment]
@yasmensarhan27 I guess the algorithm part is done. We also have to add a docstring.

**Comment by sharmistharanit** [comment]
Thanks for letting us know. @yasmensarhan27
