### ISSUE TITLE
Your code does not return time

### ISSUE THREAD

**Issue by AhmedCode99** [ubsuny/23-Homework2G5#15]
You can easily measure time by using the function time.time()

https://www.tutorialspoint.com/python/time_time.htm

**Comment by yasmensarhan27** [comment]
the code runs time in the unit test section and it is available in my repo
I'll merge it to the main repo soon

**Comment by yasmensarhan27** [comment]
can't we use %%timeit and %timeit??

**Comment by s4il3sh** [comment]
@yasmensarhan27 yes you can if you want to edit the code.

**Comment by yasmensarhan27** [comment]
I'll merge unit test using colab, quantum lab and Jupyter notebook using the original code 
Moreover, I'll add a new unit test file containing time it

Once I finish I'll request to merge them

**Comment by s4il3sh** [comment]
Sounds perfect!

**Comment by AhmedCode99** [comment]
Great
