### ISSUE TITLE
Let's choose our roles.

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework2G5#2]
Hi all,

Let's choose our roles and start working on the project. Everyone can start forking and work on it. But first, we need to choose what we will be doing. Roles are like:
- maintainer
- documentation
-  algorithm
- unit test

**Comment by s4il3sh** [comment]
According to our discussion yesterday, we have chosen our roles - 
maintainer, algorithm - s4il3sh
documentation, unit test - @yasmensarhan27 

@laserlab please assign @s4il3sh a maintainer of this group.

**Comment by yasmensarhan27** [comment]
I'm doing the  the Documentation and unit test yeah
