### ISSUE TITLE
References

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework2G5#23]
I think you have to add references for your work.

**Comment by Mosaddeq107** [comment]
Can you please identify that section?

**Comment by s4il3sh** [comment]
@sharmistharanit  you mean references inside .py file or in documentation?

**Comment by sharmistharanit** [comment]
I have referenced it by creating an md file. I am not sure if it works or not.

**Comment by yasmensarhan27** [comment]
I've added the references in the documentation you can check it in my repo
