### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework2G5#27]
@yasmensarhan27 You may start uploading documentation to our repository. And we will work on it whatever is missing.

**Comment by yasmensarhan27** [comment]
I will

**Comment by s4il3sh** [comment]
Great!

**Comment by yasmensarhan27** [comment]
I've added it to my repo please check it

**Comment by s4il3sh** [comment]
I have edited the documentation that you sent and also changed the jupyter format to markdown file.

**Comment by s4il3sh** [comment]
@yasmensarhan27 we can add a few things inside the documentation like the code under each method. There are three ways we calculate inner and outer products. So, we can mention the code for it in a general form.

Or, you can also add some things you would think it is necessary. That way you will also be a contributor to the file.

**Comment by s4il3sh** [comment]
@yasmensarhan27 the output of the documentation is not reflecting as we wanted. Can you check it again? Some of the mathematical formats are not working. You can use the preview menu while editing the code. This will help you to see what your code looks like as an output.
