### ISSUE TITLE
Docstring

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework2G5#29]
We also have to add a docstring inside our python file.

**Comment by yasmensarhan27** [comment]
I've done this in the unit test 
can you check it please

**Comment by s4il3sh** [comment]
Yes, I checked but it should be inside the Python file. I will copy-paste it, no worries.

**Comment by yasmensarhan27** [comment]
Have you changed the main code ??
shall I change the unit test then ??
why did you use time.time() although we can use %timeit

**Comment by yasmensarhan27** [comment]
please check the files that I've created and let me know if any concerns

**Comment by yasmensarhan27** [comment]
check the documentation added to the main code

**Comment by s4il3sh** [comment]
Let's say I added some code to it because it was not complete before. Yes, you need to create a unit test based on this code. And documentation part I have edited it and changed it to a markdown file. About %timeit it didn't work so I had to use time.time() function.
