### ISSUE TITLE
problem using %%timeit

### ISSUE THREAD

**Issue by yasmensarhan27** [ubsuny/23-Homework2G5#32]
when I try to run %%timeit it returns that no such command %%timeit
only %timeit that works and it's for only one line and I want to use %%timeit for more than one line to determine the time taken by the for loop

**Comment by s4il3sh** [comment]
We have to run it using time.time() code using the time module from Python. Also, the unit test seems to have a different code than our actual code, could you please copy and paste the code exactly and create a unit test from it? I guess it will work now without error.

**Comment by yasmensarhan27** [comment]
When did you change the main code ??

**Comment by AhmedCode99** [comment]
Use the time.time() method. works great:

https://www.tutorialspoint.com/python/time_time.htm
