### ISSUE TITLE
Merge and pull, Creating files and contribution. 

### ISSUE THREAD

**Issue by yasmensarhan27** [ubsuny/23-Homework2G5#38]
Hello Prof., @laserlab 
I wanted to ask if those issues will affect my grade or not.
If the original files I've created were copied in another one created by @s4il3sh and we deleted the old ones I've created. will this appear like I've no contribution?? 

@s4il3sh  has done the pull request from my repo to the main one. so, I didn't create a merge request. will this be considered as I didn't make any merge requests ??

Thank You in advance

**Comment by laserlab** [comment]
1. Files have no ownership and thus are not part of the grade.
2. Commits have authorship and thus are part of the grade, so link to the commit in question so I (and you) can see who is the author.
3. Is this the pull request you are talking about #35 ? This has you as the author and thus would be counted?

**Comment by yasmensarhan27** [comment]
Thank You for the clarifying 
no I was talking about another one

**Comment by s4il3sh** [comment]
@laserlab This is file #36 which has been changed from a jupyter notebook file to a Markdown file with some changes in it. I haven't deleted the documentation file of @yasmensarhan27 yet. If I delete the file, will her contribution go in vain?

**Comment by laserlab** [comment]
@yasmensarhan27: Your referencing a pull request #36 with is authored by @s4il3sh. It includes commit b880381237b5ded7ca5ae5d92b9ccc2c73c0d871 which is also authored by @s4il3sh So you wouldn't get points for that.

@s4il3sh This is not clear to me. all changed (or creation, even deletion) of files have to to be in a commit. So whoever commits has authorship for that particular event (change, creation, deletion). If it is committed nothing goes in vain unless somebody is deleting commits, which should be done (but even then we could restore it from the original fork)

**Comment by s4il3sh** [comment]
@laserlab No I mean, there are two files of documentation. One file was sent by @yasmensarhan27 and I modified it and created another documentation file with a different extension. So, now if I delete the previous file sent by @yasmensarhan27, she will lose all her commits and contributions to it.

**Comment by laserlab** [comment]
Can you link the commit? Again, Files do not have ownership, only commits have. If you send files around outside of commits then this information is lost. You should always go the pathway of committing your work so it is clear who made what changes (or creation or deletion)
