### ISSUE TITLE
Unit test using 3 different platforms is added

### ISSUE THREAD

**Issue by yasmensarhan27** [ubsuny/23-Homework2G5#43]
kindly check the unit test files added 
I've created a merge request

**Comment by yasmensarhan27** [comment]
@s4il3sh can you please check the merge requests?

**Comment by s4il3sh** [comment]
Yes. I did but it has conflicts. There's nothing i could do about it. Can't resolve it either.

**Comment by yasmensarhan27** [comment]
merged now ??

**Comment by s4il3sh** [comment]
yes done
