### ISSUE TITLE
Einstein notation

### ISSUE THREAD

**Issue by LinxuanHu** [ubsuny/23-Homework2G5#7]
do you have any idea about Einstein notation

**Comment by s4il3sh** [comment]
Well, Einstein's notation is about writing in a shorthand notation. For example:
![image](https://github.com/ubsuny/23-Homework2G5/assets/144289804/d69e4f6c-8d41-4ae6-a026-b4adab82d5a1)
(source: https://en.wikipedia.org/wiki/Einstein_notation)

**Comment by sharmistharanit** [comment]
Enistein's notation simplifies the writing of equations, making them more compact and easier to work with, especially in the context of physics theories that involve tensors and vector spaces.
