### ISSUE TITLE
Can you explain our homework question?

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework2G5#9]
(1. Is the homework about running matrix operations using different IDE? 
2. Is it about running the operation with various methods including Einstein notation? )
and then comparing the execution time?
1st or 2nd? which one do we need to follow? @laserlab

**Comment by poojashresthacode** [comment]
i think it is the second one..but I am not sure.

**Comment by s4il3sh** [comment]
Well, so far I have understood it's both. We perform matrix operations by writing Python code and find out its execution time. Also, our homework says about "compare" which I didn't get it. Compare with what? Any idea?

**Comment by poojashresthacode** [comment]
First of all you need to do the coding using different method.  for example by looping or ma einstein summation method. And you need to run those code and at last compare the execution time between those process.

**Comment by poojashresthacode** [comment]
https://github.com/ubsuny/CompPhys/blob/main/ReviewPython/EinsteinNotation.ipynb

or you can have a look on this

**Comment by s4il3sh** [comment]
@poojashresthacode Thanks. This makes sense to me now.

**Comment by reshnashrestha** [comment]
![image](https://github.com/ubsuny/23-Homework2G5/assets/143649458/444e8dc1-74dd-4858-a49e-c9615b627a25)
Here is the clarification from the professor.
